### ISSUE TITLE
Game crash when trying to open interface

### ISSUE THREAD

**Issue by Chefbarbie** [Xalcon/AnalyzeIO#13]
Place the machine and right click = Crash. Every time. 

FTB Beyond, latest version. All multiplayer mods and journeymap removed. 

Latest mod version.

Error: https://pastebin.com/KAfGv6YK

**Comment by Xalcon** [comment]
This is not an issue with AnalyzeIO. ~~Some other mod shades the forgelin library, which is _NOT_ a good idea. You have forgeline installed twice: Once with the wrong version, and once via another mod that shades it into its own jar (which makes it unusable for other mods).~~
Please check the version of the forgelin mod you've installed and update to 1.4.2 or higher.

// Edit:
I've checked it again. I was able to replicate the issue by installing Forgelin 1.0.5 alongside Forgelin 1.5.0. Please check your mods directory if forgelin is installed twice and remove the 1.0.5 version.

Its the same issue as in #7
