### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by yuanjie000** [Xalcon/AnalyzeIO#3]
Only add this mod to invasion ,then it [Crash](http://paste.ubuntu.com/24643802/)

**Comment by Xalcon** [comment]
I'm unable to reproduce the issue. I've downloaded the invasion modpack via the twitch launcher, unlocked the pack so i can add more mods and then added AnalyzeIO 0.3.2.
The game starts without any issues.

Also, your bug looks more like it is related to ender io recipes. Did you touch any of the EnderIO recipe files?

**Comment by yuanjie000** [comment]
I did not change any config file of EnderIO. But I use ModTweaker and CraftTweaker to change some recipes of EnderIO. I am sure this leading to crash.
