### ISSUE TITLE
GUI broken - v1.10.2-0.3.2.20

### ISSUE THREAD

**Issue by Boomflex** [Xalcon/AnalyzeIO#4]
https://gyazo.com/8447f4cb8513c17df616f9084200603c

In borderless window mode on GUI scale: Large.

**Comment by Xalcon** [comment]
I was able to reproduce this  issue with GUI Scale: Large + maximized window.... and I already have an Idea what the issue might be >_> thanks for the report

**Comment by Xalcon** [comment]
I've uploaded version 0.3.3.22 to curseforge - it should be available in a bit.
