### ISSUE TITLE
Crash when opening UI

### ISSUE THREAD

**Issue by loudwhitenoise** [Xalcon/AnalyzeIO#7]
I added this mod to Invasion, which isn't exactly the most stable of modpacks, so I wasn't too surprised to see it break. I was able to craft the device and provide it with RF, but when I right-click it, it exits the program. I did it more than once in case it was a fluke. It might be a case of me having the wrong version, as I see in the comments here that you have managed to run it on Invasion before. Anyway, here's the crashlog. https://paste.ee/p/VB5PX

**Comment by Xalcon** [comment]
I've fired up the latest version of Invasion and added AnalyzeIO 0.3.3.22, no errors for me.
I noticed you have a really, really old version of Forgelin in your pack (1.0.5). AnalyzeIO needs some special features that may only be available in later versions. I suggest updating Forgelin to version 1.4.2 or higher

**Comment by loudwhitenoise** [comment]
That was it, thank you. Works perfectly now.
